id: openid-config
info:
  name: "OpenID Connect Configuration Check"
  author: SirBugs
  severity: low
  description: "Checks for OpenID Connect configuration endpoints in /.well-known/openid-configuration."

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.well-known/openid-configuration"
    matchers:
      - type: word
        words:
          - "end_session_endpoint"
          - "token_endpoint"
          - "authorization_endpoint"
        part: body
