id: prometheus-disclose

info:
  name: prometheus Disclosure
  author: SirBugs
  severity: medium
  description: This Template checks disclosing secret information via /prometheus
  tags: prometheus, mysql

requests:
  - method: GET
    path:
      - '{{BaseURL}}/prometheus'
      - '{{BaseURL}}/prometheus/prometheus'
    matchers:
      - type: word
        part: body
        condition: or
        words:
          - 'mysql_connection_acquisition_seconds_bucket'
          - '# HELP tomcat_global_request_seconds'
          - 'logback_events_total'
          - 'jvm_memory_used_bytes'
