id: settings-py

info:
  name: settings.py Disclosure
  author: SirBugs
  severity: High
  description: This Template checks disclosing secret information via /settings.py
  tags: config, secrets, leaks, cheatset, tokens, sql, tokens

requests:
  - method: GET
    path:
      - '{{BaseURL}}/settings.py'
    matchers:
      - type: word
        part: body
        condition: or
        words:
          - 'DATABASES = {'
          - "'ENGINE':"
